# development
system:
  # 设定模式(debug/release/test,正式版改为release)
  mode: release
  # url前缀
  url-path-prefix: api
  # 程序主机地址
  host: 0.0.0.0
  # 程序监听端口
  port: 8000
  # I18国际化指定语言，值来源于i18n目录下的文件名，默认支持en和zh
  i18n-language: zh


logs:
  # 日志等级(-1:Debug, 0:Info, 1:Warn, 2:Error, 3:DPanic, 4:Panic, 5:Fatal, -1<=level<=5, 参照zap.level源码)
  level: -1
  # 日志路径
  path: logs
  # 文件最大大小, M
  max-size: 50
  # 备份数
  max-backups: 1
  # 存放时间, 天
  max-age: 30
  # 是否压缩
  compress: false

mysql:
  # 用户名
  username: root
  # 密码
  password: tanxi82694
  # 数据库名
  database: gin-vue-admin
  # 主机地址 182.61.133.217
  host: 182.61.133.217
  # 端口
  port: 3306
  # 连接字符串参数
  query: parseTime=True&loc=Local&timeout=10000ms
  # 是否打印日志
  log-mode: true
  # 编码方式
  charset: utf8mb4
  # 字符集(utf8mb4_general_ci速度比utf8mb4_unicode_ci快些)
  collation: utf8mb4_general_ci

redis:
    # 密码 123456
    password: 123456
    # 数据库名
    database: 0
    # 主机地址端口 182.61.133.217
    addr: 182.61.133.217:6379


# casbin配置
casbin:
  # 模型配置文件, config.yml相对路径
  model-path: 'config/rbac_model.conf'

# jwt配置
jwt:
  # jwt标识
  realm: Go-Vue-Admin
  # 服务端密钥
  key: 123456789
  # token过期时间, 小时
  timeout: 24
  # 刷新token最大过期时间, 小时
  max-refresh: 24

# 令牌桶限流配置
rate-limit:
  # 填充一个令牌需要的时间间隔,毫秒
  fill-interval: 100
  # 每次产生的令牌数量
  quantum: 100
  # 桶容量
  capacity: 1000
# 七牛云
qiniu:
  # AccessKey
  AccessKey: -rqxymcS3Tnb3DkfbRA5pgXJ_xLAe2OPmAzuF3sK
  # SecretKey
  SecretKey: LFHwG9a0obN_cjYOVvCHiqK16yn3e2GJbXo9UAnM
  # Bucket
  Bucket: blogtx
  # Origin
  Origin: qw80hwwsp.hd-bkt.clouddn.com
